'use client';

import Link from 'next/link';
import { use } from 'react';
import { Fragment } from 'react';
import { useEffect, useState } from 'react';
import { getDate, MatchDate } from '../../../lib/api';
import { PageTitle, PersonAvatar, Shell } from '../../components';

export default function DatePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [date, setDate] = useState<MatchDate | null>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    getDate(id).then(setDate).catch(() => setError('Conversation not found.'));
  }, [id]);

  return <Shell><section className="content">
    {error && <div className="notice">{error}</div>}
    {date && <>
      <PageTitle eyebrow="AI COMPATIBILITY SIMULATION" title="Simulated agent exchange"
        detail="This transcript was generated by AI agents from profile information; it is not a conversation involving the people described.">
        <div className="date-badges">
          <span className={`simulation-pill ${date.compatibility.simulation_mode.toLowerCase().includes('fixture') ? 'demo' : ''}`}>
            {date.compatibility.simulation_mode}
          </span>
          <span className="complete-pill"><i /> COMPLETE</span>
        </div>
      </PageTitle>
      <div className="date-participants">
        <Link href={`/people/${date.person_a.id}`} className="participant">
          <PersonAvatar person={date.person_a} />
          <span><small>AGENT A</small><b>{date.person_a.name}</b><small>{date.person_a.profession}</small></span>
        </Link>
        <div className="date-connector"><span>AGENT-TO-AGENT</span><b aria-label="interacts with">&#8597;</b></div>
        <Link href={`/people/${date.person_b.id}`} className="participant">
          <PersonAvatar person={date.person_b} />
          <span><small>AGENT B</small><b>{date.person_b.name}</b><small>{date.person_b.profession}</small></span>
        </Link>
      </div>
      <div className="conversation-layout">
        <section className="conversation">
          <div className="panel-title"><span>CONVERSATION</span><span>{date.messages.length} TURNS</span></div>
          {date.compatibility.activity?.filter(event => event.event === 'date_started').map((event, index) => <div className="activity-line" key={`start-${index}`}><i /><span>{event.message}</span><small>LIVE</small></div>)}
          {date.messages.map(message => <Fragment key={message.turn_number}>
            <article className={`message ${message.agent_person_id === date.person_a.id ? 'message-a' : 'message-b'}`}>
              <div className="message-meta"><span className="status-dot" />{message.speaker}'S AGENT<small>TURN {String(message.turn_number).padStart(2, '0')}</small></div>
              <p>{message.message}</p>
            </article>
            {date.compatibility.activity?.filter(event => event.event === 'message_generated' && event.turn_number === message.turn_number).map((event, index) => <div className="activity-line" key={`turn-${message.turn_number}-${index}`}><i /><span>{event.message}</span><small>{String(message.turn_number).padStart(2, '0')}</small></div>)}
          </Fragment>)}
          {date.compatibility.activity?.filter(event => event.event === 'compatibility_completed').map((event, index) => <div className="activity-line finished" key={`complete-${index}`}><i /><span>{event.message}</span><small>DONE</small></div>)}
        </section>
        <aside className="compat-panel">
          <div className="panel-title"><span>SIMULATED COMPATIBILITY</span><span>WEIGHTED</span></div>
          <div className="score-ring" style={{ '--score': `${date.compatibility.overall_score * 3.6}deg` } as import('react').CSSProperties}>
            <div><b>{date.compatibility.overall_score}</b><small>/ 100</small></div>
          </div>
          {Object.entries(date.compatibility.dimensions).map(([label, value]) => <div className="dimension" key={label}>
            <div><span>{label.replace('_', ' ')}</span><b>{value}</b></div><div className="meter"><i style={{ width: `${value}%` }} /></div>
          </div>)}
          <div className="insight-block"><span>STRENGTHS</span>{date.compatibility.strengths.map(item => <p key={item}>{item}</p>)}</div>
          <div className="insight-block difference"><span>DIFFERENCES</span>
            {date.compatibility.differences.length ? date.compatibility.differences.map(item => <p key={item}>{item}</p>) : <p>No strong difference signal was available.</p>}
          </div>
          <div className="insight-block"><span>SIMULATION REASON</span><p>{date.compatibility.reason}</p><p>Scores describe this AI-generated exchange, not actual dating preferences or compatibility.</p></div>
        </aside>
      </div>
    </>}
  </section></Shell>;
}
